name: ok-msg-desktop
summary: OkMSG 是由OkStar(okstar.org)社区开发和维护的注重数据安全与保护的企业通讯协同工具。
description: OkMSG 支持独立私有化部署的集即时消息、语音、视频通话、发送文件、会议等多种功能于一身的开源项目，同时让您的企业更加有效开启协作、有效沟通，控制成本，开拓新业务，并帮助您加速发展业务。
version: git
icon: src/UI/resources/logo/icon-512@2x.png
adopt-info: ok-msg

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
#  - build-on: arm64
#  - build-on: armhf
#  - build-on: ppc64el

apps:
  ok-msg-desktop:
    command: bin/desktop-launch ok-msg-desktop
    common-id: org.okstar.ok-msg-desktop
    desktop: usr/share/applications/ok-msg-desktop.desktop
    environment:
      # Tell glib to use portals on file associations handling.
      GTK_USE_PORTAL: 1
      # Use sandboxed ibus api
      IBUS_USE_PORTAL: 1
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - network
      - network-status
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  ok-msg-desktop:
    plugin: cmake
    source: .
    source-type: git
    build-packages:
      - libpcre2-dev
      - libudev-dev
      - libmtdev-dev
      - libinput-dev
      - libdrm-dev
      - libgbm-dev
      - libgtk-3-dev
      - libkrb5-dev
      - libssl-dev
      - libcrypt-dev
        # sqlite sqlcipher
      - libsodium-dev
      - libsqlite3-dev
      - libsqlcipher-dev
#      X11
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-xkb-dev
      - libxcb-xv0-dev
      - libxkbcommon-x11-dev
      - libxkbcommon-dev
      - libxkbfile-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxss-dev
        # Multimedia
      - libasound2-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libpulse-dev
      - libpulse-mainloop-glib0
      - libopenal-dev
#      FFMPEG
      - libvpx-dev
      - libjpeg-dev
      - libexif-dev
      - libtiff-dev
      - libpng16-16
      - libpng-dev
      - libavcodec-dev
      - libavdevice-dev
      - libqrencode-dev
#      Qt
      - qtbase5-dev
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - libqt5xml5
      - libqt5xmlpatterns5-dev
      - libqt5opengl5-dev
      - qttools5-dev
      - qttools5-dev-tools
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DDESKTOP_APP_USE_PACKAGED=ON
      - -DDESKTOP_APP_USE_PACKAGED_LAZY=ON
      - -DDESKTOP_LAUNCHER_BASENAME=ok-msg-desktop