name: ok-msg-desktop
adopt-info: ok-msg
icon: src/UI/resources/logo/icon-512@2x.png

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
#  - build-on: arm64
#  - build-on: armhf
#  - build-on: ppc64el

apps:
  ok-msg-desktop:
    command: bin/desktop-launch ok-msg-desktop
    common-id: org.okstar.ok-msg-desktop
    desktop: usr/share/applications/okstar_ok-msg-desktop.desktop
    environment:
      # Tell glib to use portals on file associations handling.
      GTK_USE_PORTAL: 1
      # Use sandboxed ibus api
      IBUS_USE_PORTAL: 1
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - network
      - network-status
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  ok-msg-desktop:
    plugin: cmake
    source: .
    source-type: git
    build-packages:
      - libpcre2-dev
      - libudev-dev
      - libmtdev-dev
      - libinput-dev
      - libdrm-dev
      - libgbm-dev
      - libgtk-3-dev
      - libkrb5-dev
      - libssl-dev
      - libcrypt-dev
      - libsodium-dev
      - libsqlite3-dev
      - libsqlcipher-dev
      - libxcb*
      - libxkb*
      - libfontconfig1-dev
      - libfreetype6-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxss-dev
        # Multimedia
      - libasound2-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libpulse-dev
      - libpulse-mainloop-glib0
      - libopenal-dev
        # sqlite sqlcipher
      - libsqlite3-dev
      - libsqlcipher-dev
#      FFMPEG
      - libvpx-dev
      - libjpeg-dev
      - libexif-dev
      - libtiff-dev
      - libpng16-16
      - libpng-dev
      - libavcodec-dev
      - libavdevice-dev
      - libqrencode-dev
      - libsodium-dev
      - libopenal-dev
#      Qt
      - qtbase5-dev
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - libqt5xml5
      - libqt5xmlpatterns5-dev
      - libqt5opengl5-dev
      - linguist-qt5
      - linguist-qt6