name: ok-msg-desktop
summary: OkMSG 是由OkStar(okstar.org)社区开发和维护的注重数据安全与保护的企业通讯协同工具。
description: OkMSG 支持独立私有化部署的集即时消息、语音、视频通话、发送文件、会议等多种功能于一身的开源项目，同时让您的企业更加有效开启协作、有效沟通，控制成本，开拓新业务，并帮助您加速发展业务。
version: git
icon: src/UI/resources/logo/icon-512@2x.png
adopt-info: ok-msg

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
#  - build-on: arm64
#  - build-on: armhf
#  - build-on: ppc64el

apps:
  ok-msg-desktop:
    command: ok-msg-desktop
    common-id: org.okstar.ok-msg-desktop
    desktop: usr/share/applications/ok-msg-desktop.desktop
    environment:
      # Tell glib to use portals on file associations handling.
      GTK_USE_PORTAL: 1
      # Use sandboxed ibus api
      IBUS_USE_PORTAL: 1
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - network
      - network-status
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  ok-msg-desktop:
    plugin: cmake
    source: .
    source-type: git
    parse-info: [ usr/share/metainfo/ok-msg-desktop.metainfo.xml ]
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    build-packages:
      - libpcre2-dev
      - libudev-dev
      - libmtdev-dev
      - libinput-dev
      - libdrm-dev
      - libgbm-dev
      - libgtk-3-dev
      - freeglut3-dev
      - libkrb5-dev
        # sqlite sqlcipher
      - libssl-dev
      - libcrypt-dev
      - libsodium-dev
      - libsqlite3-dev
      - libsqlcipher-dev
#      X11
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-xf86dri0-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-xinput-dev
      - libxcb-xkb-dev
      - libxcb-xrm-dev
      - libxcb-xtest0-dev
      - libxcb-xv0-dev
      - libxcb-xvmc0-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxkbcommon-x11-dev
      - libxkbcommon-dev
      - libxkbfile-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxss-dev
        # Multimedia
      - libasound2-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libpulse-dev
      - libpulse-mainloop-glib0
      - libopenal-dev
#      FFMPEG
      - libvpx-dev
      - libjpeg-dev
      - libexif-dev
      - libtiff-dev
      - libpng16-16
      - libpng-dev
      - libavcodec-dev
      - libavdevice-dev
      - libqrencode-dev
#      Qt
      - qtbase5-dev
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - libqt5xml5
      - libqt5xmlpatterns5-dev
      - libqt5opengl5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libsignal-protocol-c-dev
    stage-packages:
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libqt5svg5
      - libqt5xml5
      - libsdl2-2.0-0
      - libdouble-conversion3
      - libmd4c0
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libglib2.0-0
      - libglx0
      - libgl1
      - libglu1-mesa
      - freeglut3
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu70
      - libopengl0
      - libpcre2-16-0
      - libpng16-16
      - libsm6
      - libvulkan1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxv1
      - libxss1
      - zlib1g
      - libflac8
      - ocl-icd-libopencl1
      - libaom3
      - libasound2
      - libasyncns0
      - libavc1394-0
      - libavcodec58
      - libavdevice58
      - libavfilter7
      - libavformat58
      - libavutil56
      - libblas3
      - libbluray2
      - libbs2b0
      - libcaca0
      - libcdio19
      - libcdio-cdda2
      - libcdio-paranoia2
      - libchromaprint1
      - libcodec2-1.0
      - libdav1d5
      - libdc1394-25
      - libdecor-0-0
      - libexif12
      - libflite1
      - libgfortran5
      - libgme0
      - libgomp1
      - libgsm1
      - libiec61883-0
      - libjack-jackd2-0
      - liblapack3
      - liblilv-0-0
      - libmfx1
      - libmp3lame0
      - libmpg123-0
      - libmysofa1
      - libnorm1
      - libnuma1
      - libogg0
      - libopenal1
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libpgm-5.3-0
      - libpocketsphinx3
      - libpostproc55
      - libpulse0
      - libqrencode4
      - libquadmath0
      - libvpx7
      - libwebpmux3
      - libx264-163
      - libx265-199
      - libswscale5
      - libswresample3
      - libsqlcipher0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libspeex1
      - freeglut3
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DDESKTOP_APP_USE_PACKAGED=ON
      - -DDESKTOP_LAUNCHER_BASENAME=ok-msg-desktop
    prime:
      - -./usr/bin
      - -./usr/doc
      - -./usr/include
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/metatypes
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.so
      - -./usr/libexec
      - -./usr/mkspecs
      - -./usr/modules