name: ok-msg-desktop
adopt-info: ok-msg
icon: src/UI/resources/logo/icon-512@2x.png

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
#  - build-on: arm64
#  - build-on: armhf
#  - build-on: ppc64el

apps:
  ok-msg-desktop:
    command: bin/desktop-launch ok-msg-desktop
    common-id: org.okstar.ok-msg-desktop
    desktop: usr/share/applications/okstar_ok-msg-desktop.desktop
    environment:
      # Tell glib to use portals on file associations handling.
      GTK_USE_PORTAL: 1
      # Use sandboxed ibus api
      IBUS_USE_PORTAL: 1
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - network
      - network-status
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  ok-msg-desktop:
    plugin: cmake
    source: .
    source-type: git
    after:
      - desktop-qt
  desktop-qt:
    source: https://github.com/desktop-app/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: [ "FLAVOR=qt5" ]
    build-packages:
      - build-essential
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs
    stage:
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    after:
      - qt
  qt:
    plugin: nil
    build-packages:
      - libdbus-1-dev
      - libegl-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libglib2.0-dev
      - libglx-dev
      - libgtk-3-dev
      - libharfbuzz-dev
      - libice-dev
      - libicu-dev
      - libopengl-dev
      - libpcre2-dev
      - libpng-dev
      - libsm-dev
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-render-util0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-util-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxcursor-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - zlib1g-dev
    stage-packages:
      - libdbus-1-3
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libglib2.0-0
      - libglx0
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu70
      - libopengl0
      - libpcre2-16-0
      - libpng16-16
      - libsm6
      - libvulkan1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-util1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - zlib1g
    override-pull: |
      QT=6_4_0

      git clone -b v6.4.0 --depth=1 git://code.qt.io/qt/qt5.git .
      perl init-repository --module-subset=qtbase,qtwayland,qtimageformats,qtsvg,qt5compat

      cd qtbase
      find $CRAFT_STAGE/patches/qtbase_${QT} -type f -print0 | sort -z | xargs -r0 git apply
      cd ..
    override-build: |
      ./configure \
        -prefix /usr \
        -libdir /usr/lib/$CRAFT_ARCH_TRIPLET \
        -release \
        -opensource \
        -confirm-license \
        -no-feature-getentropy \
        -no-feature-renameat2 \
        -no-feature-statx \
        -no-feature-egl-extension-platform-wayland \
        -no-feature-wayland-server \
        -no-feature-highdpiscaling \
        -openssl-linked \
        -nomake examples \
        -nomake tests

      cmake --build . -j$CRAFT_PARALLEL_BUILD_COUNT
      DESTDIR="$CRAFT_PART_INSTALL" cmake --install .
    stage:
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/libjpeg.so.8.2.2
    prime:
      - -./usr/bin
      - -./usr/doc
      - -./usr/include
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/metatypes
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.a
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.la
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.prl
      - -./usr/lib/$CRAFT_ARCH_TRIPLET/*.so
      - -./usr/libexec
      - -./usr/mkspecs
      - -./usr/modules